In [ ]:
import numpy as np
# Python was created by a Dutch programmer named Guido van Rossum,
# while NumPy was created by an American data scientist named Travis Oliphant around 2004 2005.

In [ ]:
l=[1,'ok',2.5,True]
l*2

[1, 'ok', 2.5, True, 1, 'ok', 2.5, True]

In [ ]:
d=np.array([1,2,3,4]) #1D array
p=np.array([1,2,3,4,5.5]) #will convert to same float datatype
print(d,p)
print(type(d),type(p))
print(d.dtype,p.dtype)



[1 2 3 4] [1.  2.  3.  4.  5.5]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
int64 float64


In [ ]:
m=np.array([1,True,'ok',10.10])
m

array(['1', 'True', 'ok', '10.1'], dtype='<U32')

Numpy is useful for Image or vision processing

In [ ]:
import pandas as pd
df=pd.read_csv('/content/Retail_Dataset_Modified.csv')
print(df)

            Store_ID                       Store_Name    Brand_Name  \
0        BX_PUNE_034     BrandX_India Superstore Pune  BrandX_India   
1      BX_MUMBAI_023   BrandX_India Superstore Mumbai  BrandX_India   
2        BX_PUNE_073         BrandX_India Trends Pune  BrandX_India   
3     BX_CHENNAI_061      BrandX_India Trends Chennai  BrandX_India   
4     BX_CHENNAI_033     BrandX_India Connect Chennai  BrandX_India   
...              ...                              ...           ...   
5166   BX_JAIPUR_077        BrandX_India Style Jaipur  BrandX_India   
5167   BX_MUMBAI_067        BrandX_India Daily Mumbai  BrandX_India   
5168   BX_KANPUR_097  BrandX_India Gadget Zone Kanpur  BrandX_India   
5169   BX_MUMBAI_031        BrandX_India Style Mumbai  BrandX_India   
5170    BX_DELHI_032   BrandX_India Electronics Delhi  BrandX_India   

        Store_Type     City City_Tier     Product_Name     Category  \
0         Flagship     Pune     Tier1   Green Tea 100g    Groceries   
1    

In [ ]:
df

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter


In [ ]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring


In [ ]:
df.head(3)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring


In [ ]:
df.head(9)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
5,BX_DELHI_082,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Toor Dal 1kg,Groceries,Dal,New Launch,...,81.3,85.3,Aggressive,Low,4.0,108,1,2022,Q1,Spring
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,98.0,81.6,Competitive,Low,2.0,90,1,2022,Q1,Spring
7,BX_DELHI_062,BrandX_India Digital Delhi,BrandX_India,Mall Store,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Mature,...,81.6,82.4,Competitive,Low,3.0,137,1,2022,Q1,Spring
8,BX_MUMBAI_042,BrandX_India Appliances Mumbai,BrandX_India,Street Store,Mumbai,Metro,NaN,Home Appliances,Water Purifiers,Declining,...,96.3,82.7,Aggressive,Low,4.0,214,1,2022,Q1,Spring


In [ ]:
df.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon


In [ ]:
df.tail(7)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5164,BX_MUMBAI_020,BrandX_India Gadget Zone Mumbai,BrandX_India,Street Store,Mumbai,Metro,LG OLED 55Inch,Electronics,Smart TVs,Declining,...,79.6,88.4,Competitive,Low,1.0,101,8,2024,Q3,Monsoon
5165,BX_CHENNAI_047,BrandX_India Fresh Chennai,BrandX_India,Online Hub,Chennai,Metro,Moong Dal 1kg,Groceries,Dal,Mature,...,79.7,89.8,Aggressive,Low,2.0,99,1,2024,Q1,Spring
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon


In [ ]:
df.shape # (row,column)

(5171, 47)

In [ ]:
df.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [ ]:
df.rows #no for rows, you can see shape

AttributeError: 'DataFrame' object has no attribute 'rows'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Store_ID               5171 non-null   object 
 1   Store_Name             5171 non-null   object 
 2   Brand_Name             5171 non-null   object 
 3   Store_Type             5171 non-null   object 
 4   City                   5109 non-null   object 
 5   City_Tier              5171 non-null   object 
 6   Product_Name           5098 non-null   object 
 7   Category               5171 non-null   object 
 8   Sub_Category           5171 non-null   object 
 9   Product_Stage          5171 non-null   object 
 10  Quantity_Available     5171 non-null   object 
 11  Units_Sold             5171 non-null   object 
 12  Unit_Price             5171 non-null   int64  
 13  Cost_Price             5171 non-null   int64  
 14  Revenue                5099 non-null   object 
 15  Prof

In [ ]:
df.describe()

,Unit_Price,Cost_Price,Profit_Margin,Average_Order_Value,Inventory_Turnover,Days_of_Stock,Promotion_Impact,Max_Discount_Offered,Return_Rate,Customer_Satisfaction,...,Review_Count,Sales_Rep_Experience,Sales_Rep_Rating,Market_Share,Competitor_Count,Brand_Loyalty,Brand_Awareness,Delivery_Time,Month,Year
count,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5094.000000,...,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5111.000000,5171.000000,5171.000000
mean,36147.283117,28008.718236,22.455080,45000.251789,3.928517,142.718816,20.979791,22.679172,4.018294,4.209109,...,256.498936,5.548250,4.248018,15.406556,16.231483,81.351228,80.307097,3.984934,6.567588,2023.016438
std,53910.395954,41848.286241,4.349469,67405.809814,2.284159,128.281114,12.212204,15.784690,2.292903,0.280465,...,140.948535,2.861696,0.433274,6.009766,6.646939,8.018098,8.542352,2.021598,3.463351,0.814235
min,36.000000,28.000000,14.680000,41.000000,0.300000,32.000000,0.000000,0.000000,0.000000,3.600000,...,10.000000,1.000000,3.500000,3.000000,3.000000,67.000000,60.000000,1.000000,1.000000,2022.000000
25%,2016.500000,1548.500000,18.675000,2476.000000,2.220000,68.000000,13.100000,9.000000,2.000000,4.000000,...,138.000000,3.000000,3.900000,11.300000,11.000000,75.900000,77.700000,2.000000,4.000000,2022.000000
50%,11816.000000,9136.000000,22.450000,14734.000000,3.440000,105.000000,22.300000,22.000000,4.100000,4.200000,...,256.000000,6.000000,4.200000,14.900000,18.000000,80.400000,83.000000,4.000000,7.000000,2023.000000
75%,53778.500000,41569.000000,26.235000,66630.000000,5.260000,162.000000,31.200000,36.000000,6.000000,4.400000,...,378.000000,8.000000,4.600000,18.900000,22.000000,84.600000,86.600000,6.000000,10.000000,2024.000000
max,307651.000000,252171.000000,30.430000,450890.000000,11.100000,1200.000000,40.000000,50.000000,8.000000,4.900000,...,500.000000,10.000000,5.000000,30.000000,25.000000,100.000000,90.000000,7.000000,12.000000,2024.000000


In [ ]:
dxls=pd.read_excel('/content/Formatting.xlsx')
dxls

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
0,2020-01-01,East,Boston,Bars,Carrot,33,1.77,58.41
1,2020-01-04,East,Boston,Crackers,Whole Wheat,87,3.49,303.63
2,2020-01-07,West,Los Angeles,Cookies,Chocolate Chip,58,1.87,108.46
3,2020-01-10,East,New York,Cookies,Chocolate Chip,82,1.87,153.34
4,2020-01-13,East,Boston,Cookies,Arrowroot,38,2.18,82.84
...,...,...,...,...,...,...,...,...
239,2021-12-18,East,Boston,Cookies,Arrowroot,34,2.18,74.12
240,2021-12-21,East,Boston,Cookies,Chocolate Chip,245,1.87,458.15
241,2021-12-24,East,Boston,Crackers,Whole Wheat,30,3.49,104.70
242,2021-12-27,West,Los Angeles,Bars,Bran,30,1.87,56.10


df.columns ---- here columns is attribute

df.info() ---- here info() is method

In [ ]:
idd=[123,456,789,2526]
name=['Diva','Mahesh','Rakesh','Vikky']
age=[20,25,18,10]
vb=pd.DataFrame({'Name':name,'Age':age}) # this DataFrame is for not one-dimension
ao=pd.Series(age) # this Series is for one-dimension
vb

,Name,Age
0,Diva,20
1,Mahesh,25
2,Rakesh,18
3,Vikky,10


In [ ]:
print(ao)

0    20
1    25
2    18
3    10
dtype: int64


In [ ]:
ao

,0
0,20
1,25
2,18
3,10


In [ ]:
idt=[12,34,56,78]
cdt=[11,22,33,44]
ao1=pd.Series(idt,cdt)
ao1

,0
11,12
22,34
33,56
44,78


In [ ]:
print(type(ao1),
type(ao),
type(vb))

<class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'> <class 'pandas.core.frame.DataFrame'>


In [ ]:
type(vb)

pandas.core.frame.DataFrame

In [ ]:
at=[1,2,3]
ao2=pd.Series({'ao':at})
ao2

,0
ao,"[1, 2, 3]"


In [ ]:
print(type(ao2),ao2.shape)

<class 'pandas.core.series.Series'> (1,)


In [ ]:
ao2.isnull()

,0
ao,False


In [ ]:
vb.isnull()

,Name,Age
0,False,False
1,False,False
2,False,False
3,False,False


In [ ]:
vb.isnull().sum()

,0
Name,0
Age,0


In [ ]:
ao.isnull()

,0
0,False
1,False
2,False
3,False


In [ ]:
id3=[123,456,789]
name3=['Diva','Mahesh','Rakesh','Vikky']
age3=[20,25,18,10]
vb3=pd.DataFrame({'ID3':id3,'Age':age}) #un even data lenght for both
ao3=pd.Series(name)
vb3

ValueError: All arrays must be of the same length

In [ ]:
id3=[123,456,789,nan]
name3=['Diva','Mahesh','Rakesh','Vikky']
age3=[20,25,18,10]
vb3=pd.DataFrame({'ID3':id3,'Age':age}) #un even data lenght for both
ao3=pd.Series(name)
vb3

NameError: name 'nan' is not defined

In [ ]:
id3=[123,456,789,NaN]
name3=['Diva','Mahesh','Rakesh','Vikky']
age3=[20,25,18,10]
vb3=pd.DataFrame({'ID3':id3,'Age':age}) #un even data lenght for both
ao3=pd.Series(name)
vb3

NameError: name 'NaN' is not defined

In [ ]:
id4=[123,456,789,np.nan]
name4=['Diva','Mahesh','Rakesh','Vikky']
age4=[20,25,18,10]
vb4=pd.DataFrame({'ID3':id3,'Age':age}) #un even data lenght for both
ao4=pd.Series(name)
vb4

,ID3,Age
0,123.0,20
1,456.0,25
2,789.0,18
3,NaN,10


In [ ]:
vb4.isnull()

,ID3,Age
0,False,False
1,False,False
2,False,False
3,True,False


In [ ]:
import pandas as pd
df0=pd.read_csv('/content/online-retail-dataset.csv')
df0

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France


In [ ]:
#Pandas found by Wes McKinney around 2009

In [3]:
import numpy as np
e=np.array([1,2,3,4])
e.ndim   #gives dimension of array

1

In [4]:
r=np.array(6)
print(r,r.ndim)

6 0


In [8]:
p=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(p.ndim)
print(p)
print(p[0:3][1:])  #all rows but from 1 index
print(p[0:3,1:])   #all rows but excluding 0 index column

2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [11]:
print(p.astype('float'),p.astype('str'),p,sep='\n')

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
import pandas as pd
df0=pd.read_csv('/content/sample_data/california_housing_test.csv')
df0.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [14]:
df0['households','latitude']

KeyError: ('households', 'latitude')

In [15]:
df0['households']

,households
0,606.0
1,277.0
2,495.0
3,11.0
4,237.0
...,...
2995,607.0
2996,1036.0
2997,220.0
2998,14.0


In [16]:
df0[['households','latitude']]

,households,latitude
0,606.0,37.37
1,277.0,34.26
2,495.0,33.78
3,11.0,33.82
4,237.0,36.33
...,...,...
2995,607.0,34.42
2996,1036.0,34.06
2997,220.0,36.30
2998,14.0,34.10


In [21]:
df0.select_dtypes(exclude='float') #all dtypes are floats that's why its empty

""
0
1
2
3
4
...
2995
2996
2997
2998


In [22]:
df1=pd.read_csv('/content/Retail_Dataset_Modified.csv')
df1.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [25]:
df1.select_dtypes(exclude='object')

,Unit_Price,Cost_Price,Profit_Margin,Average_Order_Value,Inventory_Turnover,Days_of_Stock,Promotion_Impact,Max_Discount_Offered,Return_Rate,Customer_Satisfaction,...,Review_Count,Sales_Rep_Experience,Sales_Rep_Rating,Market_Share,Competitor_Count,Brand_Loyalty,Brand_Awareness,Delivery_Time,Month,Year
0,305,239,21.64,432,2.30,156,23.1,9,3.1,4.0,...,53,5,4.8,15.3,8,70.8,75.7,6.0,1,2022
1,47,33,29.79,63,3.11,116,34.9,21,2.9,3.9,...,202,10,3.6,18.9,25,80.5,81.5,4.0,1,2022
2,2140,1715,19.86,2994,1.73,208,29.4,36,6.3,4.3,...,77,1,4.0,14.2,11,68.5,76.7,4.0,1,2022
3,3534,2894,18.11,4416,1.62,222,37.3,31,4.0,4.4,...,221,7,3.9,16.4,19,92.4,88.0,5.0,1,2022
4,50676,40467,20.15,54629,2.80,128,33.1,43,4.8,3.9,...,205,6,4.9,13.4,19,82.9,89.5,2.0,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,2373,1972,16.90,2617,0.45,797,37.9,48,7.9,4.2,...,368,6,4.9,10.9,7,91.3,68.7,3.0,11,2024
5167,54,43,20.37,58,3.85,93,34.5,13,5.0,3.7,...,424,3,4.8,14.1,21,81.6,82.0,7.0,7,2023
5168,75554,52990,29.86,94881,1.77,203,0.0,0,5.3,3.9,...,326,6,3.8,11.3,6,89.9,68.1,1.0,7,2023
5169,11102,9267,16.53,16105,1.61,224,29.1,30,4.0,4.4,...,73,1,3.6,12.5,17,80.6,86.5,3.0,12,2022


In [27]:
df1['Store_Name']

,Store_Name
0,BrandX_India Superstore Pune
1,BrandX_India Superstore Mumbai
2,BrandX_India Trends Pune
3,BrandX_India Trends Chennai
4,BrandX_India Connect Chennai
...,...
5166,BrandX_India Style Jaipur
5167,BrandX_India Daily Mumbai
5168,BrandX_India Gadget Zone Kanpur
5169,BrandX_India Style Mumbai


In [32]:
df1['Store_Name'][0:10].str.upper()

,Store_Name
0,BRANDX_INDIA SUPERSTORE PUNE
1,BRANDX_INDIA SUPERSTORE MUMBAI
2,BRANDX_INDIA TRENDS PUNE
3,BRANDX_INDIA TRENDS CHENNAI
4,BRANDX_INDIA CONNECT CHENNAI
5,BRANDX_INDIA SUPERSTORE DELHI
6,BRANDX_INDIA ACCESSORIES MUMBAI
7,BRANDX_INDIA DIGITAL DELHI
8,BRANDX_INDIA APPLIANCES MUMBAI
9,BRANDX_INDIA STYLE NAGPUR


In [33]:
df1['Store_Name'][0].upper()

'BRANDX_INDIA SUPERSTORE PUNE'

In [34]:
for t in df1['Store_Name'][0:10]:
  print(t.upper())

BRANDX_INDIA SUPERSTORE PUNE
BRANDX_INDIA SUPERSTORE MUMBAI
BRANDX_INDIA TRENDS PUNE
BRANDX_INDIA TRENDS CHENNAI
BRANDX_INDIA CONNECT CHENNAI
BRANDX_INDIA SUPERSTORE DELHI
BRANDX_INDIA ACCESSORIES MUMBAI
BRANDX_INDIA DIGITAL DELHI
BRANDX_INDIA APPLIANCES MUMBAI
BRANDX_INDIA STYLE NAGPUR


In [35]:
df1['Unit_Price'][:10].sum()

np.int64(229462)

In [36]:
df1['Unit_Price'][:10].max()

103410

In [37]:
print(sum(df1['Unit_Price'][:10]),max(df1['Unit_Price'][:10]))

229462 103410
